
services:
  jupyter:
    image: nvcr.io/nvidia/pytorch:25.08-py3
    build: .
    container_name: torch-jupyter
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ports:
      - "8888:8888"
    env_file:
      - .env
    working_dir: /app
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    volumes:
      # 👇 mount Windows folder into /app
      - "YOUR FOLDER NAME HERE:/app"